platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((spring-credhub-virtual-docker-registry))/docker
    tag: 26-cli
    username: ((broadcom-jfrog-artifactory-robot-account.username))
    password: ((broadcom-jfrog-artifactory-robot-account.password))

inputs:
  - name: git-repo

outputs:
  - name: docker-config

run:
  path: ci/scripts/generate-docker-credentials.sh
  dir: git-repo

params:
  DOCKER_CONFIG_OUTPUT: ../docker-config
  REGISTRY: ((spring-credhub-virtual-docker-registry))
  REGISTRY_USERNAME: ((broadcom-jfrog-artifactory-robot-account.username))
  REGISTRY_PASSWORD: ((broadcom-jfrog-artifactory-robot-account.password))
